{{- range $name, $svc := .Values.services }}
{{- if and $svc.persistence $svc.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "portfolio-insights.fullname" $ }}-{{ $name }}-pvc
  labels:
    {{- include "portfolio-insights.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  accessModes:
    - {{ $svc.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $svc.persistence.size }}
{{- end }}
{{- end }}
