run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - disableStutteringCheck
      - name: package-comments
        severity: warning
        disabled: false



issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
