// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Holding struct {
	Symbol             string  `json:"symbol"`
	Quantity           float64 `json:"quantity"`
	AveragePrice       float64 `json:"averagePrice"`
	CurrentPrice       float64 `json:"currentPrice"`
	CurrentValue       float64 `json:"currentValue"`
	GainLoss           float64 `json:"gainLoss"`
	GainLossPercentage float64 `json:"gainLossPercentage"`
	Currency           string  `json:"currency"`
	AssetName          string  `json:"assetName"`
}

type Mutation struct {
}

type NewTransaction struct {
	Symbol            string          `json:"symbol"`
	Quantity          float64         `json:"quantity"`
	PricePerShare     float64         `json:"pricePerShare"`
	ExecutedAt        string          `json:"executedAt"`
	Type              TransactionType `json:"type"`
	Notes             *string         `json:"notes,omitempty"`
	Brokerage         *float64        `json:"brokerage,omitempty"`
	PriceCurrency     *string         `json:"priceCurrency,omitempty"`
	BrokerageCurrency *string         `json:"brokerageCurrency,omitempty"`
}

type NewUser struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Portfolio struct {
	ID       string            `json:"id"`
	UserID   string            `json:"userId"`
	Name     string            `json:"name"`
	Summary  *PortfolioSummary `json:"summary,omitempty"`
	Holdings []*Holding        `json:"holdings"`
}

type PortfolioPerformancePoint struct {
	Timestamp string  `json:"timestamp"`
	Value     float64 `json:"value"`
}

type PortfolioSummary struct {
	TotalValue              float64 `json:"totalValue"`
	TotalGainLoss           float64 `json:"totalGainLoss"`
	TotalGainLossPercentage float64 `json:"totalGainLossPercentage"`
	DayChange               float64 `json:"dayChange"`
	DayChangePercentage     float64 `json:"dayChangePercentage"`
	Currency                string  `json:"currency"`
	LastUpdated             string  `json:"lastUpdated"`
	StartDate               *string `json:"startDate,omitempty"`
	EndDate                 *string `json:"endDate,omitempty"`
	CapitalGain             float64 `json:"capitalGain"`
	CapitalGainPercentage   float64 `json:"capitalGainPercentage"`
	CurrencyGain            float64 `json:"currencyGain"`
	CurrencyGainPercentage  float64 `json:"currencyGainPercentage"`
	Dividends               float64 `json:"dividends"`
	DividendsPercentage     float64 `json:"dividendsPercentage"`
}

type Query struct {
}

type Transaction struct {
	ID                string          `json:"id"`
	UserID            string          `json:"userId"`
	Symbol            string          `json:"symbol"`
	Type              TransactionType `json:"type"`
	Quantity          float64         `json:"quantity"`
	PricePerShare     float64         `json:"pricePerShare"`
	ExecutedAt        string          `json:"executedAt"`
	Notes             *string         `json:"notes,omitempty"`
	Brokerage         *float64        `json:"brokerage,omitempty"`
	PriceCurrency     *string         `json:"priceCurrency,omitempty"`
	BrokerageCurrency *string         `json:"brokerageCurrency,omitempty"`
	CreatedAt         string          `json:"createdAt"`
	UpdatedAt         string          `json:"updatedAt"`
}

type TransactionConnection struct {
	Transactions  []*Transaction `json:"transactions"`
	NextPageToken *string        `json:"nextPageToken,omitempty"`
}

type TransactionFilterInput struct {
	Symbol         *string          `json:"symbol,omitempty"`
	Type           *TransactionType `json:"type,omitempty"`
	FromExecutedAt *string          `json:"fromExecutedAt,omitempty"`
	ToExecutedAt   *string          `json:"toExecutedAt,omitempty"`
}

type User struct {
	ID          string                 `json:"id"`
	Username    string                 `json:"username"`
	Email       string                 `json:"email"`
	FirstName   string                 `json:"firstName"`
	LastName    string                 `json:"lastName"`
	Role        string                 `json:"role"`
	Preferences map[string]interface{} `json:"preferences,omitempty"`
	LastLoginAt *string                `json:"lastLoginAt,omitempty"`
}

type TransactionType string

const (
	TransactionTypeBuy      TransactionType = "BUY"
	TransactionTypeSell     TransactionType = "SELL"
	TransactionTypeSplit    TransactionType = "SPLIT"
	TransactionTypeDividend TransactionType = "DIVIDEND"
)

var AllTransactionType = []TransactionType{
	TransactionTypeBuy,
	TransactionTypeSell,
	TransactionTypeSplit,
	TransactionTypeDividend,
}

func (e TransactionType) IsValid() bool {
	switch e {
	case TransactionTypeBuy, TransactionTypeSell, TransactionTypeSplit, TransactionTypeDividend:
		return true
	}
	return false
}

func (e TransactionType) String() string {
	return string(e)
}

func (e *TransactionType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionType", str)
	}
	return nil
}

func (e TransactionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
