// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Holding struct {
	Symbol   string  `json:"symbol"`
	Quantity float64 `json:"quantity"`
	Value    float64 `json:"value"`
}

type Mutation struct {
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Portfolio struct {
	ID       string     `json:"id"`
	UserID   string     `json:"userId"`
	Name     string     `json:"name"`
	Holdings []*Holding `json:"holdings"`
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
