// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Holding struct {
	Symbol             string  `json:"symbol"`
	Quantity           float64 `json:"quantity"`
	AveragePrice       float64 `json:"averagePrice"`
	CurrentPrice       float64 `json:"currentPrice"`
	CurrentValue       float64 `json:"currentValue"`
	GainLoss           float64 `json:"gainLoss"`
	GainLossPercentage float64 `json:"gainLossPercentage"`
	Currency           string  `json:"currency"`
}

type Mutation struct {
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Portfolio struct {
	ID       string            `json:"id"`
	UserID   string            `json:"userId"`
	Name     string            `json:"name"`
	Summary  *PortfolioSummary `json:"summary,omitempty"`
	Holdings []*Holding        `json:"holdings"`
}

type PortfolioSummary struct {
	TotalValue              float64 `json:"totalValue"`
	TotalGainLoss           float64 `json:"totalGainLoss"`
	TotalGainLossPercentage float64 `json:"totalGainLossPercentage"`
	Currency                string  `json:"currency"`
	LastUpdated             string  `json:"lastUpdated"`
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
