package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/garcios/portfolio-insights/apps/gateway/graph/generated"
	"github.com/garcios/portfolio-insights/apps/gateway/graph/model"
	portfoliopb "github.com/garcios/portfolio-insights/services/portfolio-service/proto/portfolio"
	userpb "github.com/garcios/portfolio-insights/services/user-service/proto/user"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	req := &userpb.CreateUserRequest{
		Email:    input.Email,
		Name:     input.Username,
		Password: "defaultPassword123", // In production, this should come from input
	}

	resp, err := r.UserClient.CreateUser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	return &model.User{
		ID:       resp.Id,
		Username: input.Username,
		Email:    input.Email,
	}, nil
}

// Summary is the resolver for the summary field.
func (r *portfolioResolver) Summary(ctx context.Context, obj *model.Portfolio) (*model.PortfolioSummary, error) {
	// This resolver only executes if the query requests the summary field
	summaryReq := &portfoliopb.GetPortfolioSummaryRequest{
		UserId: obj.UserID,
	}

	summaryResp, err := r.PortfolioClient.GetPortfolioSummary(ctx, summaryReq)
	if err != nil {
		// Return nil for optional field if it fails
		return nil, nil
	}

	if summaryResp.Summary == nil {
		return nil, nil
	}

	return &model.PortfolioSummary{
		TotalValue:              summaryResp.Summary.TotalValue,
		TotalGainLoss:           summaryResp.Summary.TotalGainLoss,
		TotalGainLossPercentage: summaryResp.Summary.TotalGainLossPercentage,
		Currency:                summaryResp.Summary.Currency,
		LastUpdated:             summaryResp.Summary.LastUpdated.AsTime().Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}

// Holdings is the resolver for the holdings field.
func (r *portfolioResolver) Holdings(ctx context.Context, obj *model.Portfolio) ([]*model.Holding, error) {
	// This resolver only executes if the query requests the holdings field
	holdingsReq := &portfoliopb.GetHoldingsRequest{
		UserId: obj.UserID,
	}

	holdingsResp, err := r.PortfolioClient.GetHoldings(ctx, holdingsReq)
	if err != nil {
		return nil, fmt.Errorf("failed to get holdings: %w", err)
	}

	var holdings []*model.Holding
	for _, h := range holdingsResp.Holdings {
		holdings = append(holdings, &model.Holding{
			Symbol:             h.Symbol,
			Quantity:           h.Quantity,
			AveragePrice:       h.AveragePrice,
			CurrentPrice:       h.CurrentPrice,
			CurrentValue:       h.CurrentValue,
			GainLoss:           h.GainLoss,
			GainLossPercentage: h.GainLossPercentage,
			Currency:           h.Currency,
			AssetName:          h.AssetName,
		})
	}

	return holdings, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// For now, return a hardcoded user ID
	// In production, this should come from authentication context
	userID := "3a4b3185-5abb-4899-9835-829ddb91e3a6"
	return r.User(ctx, userID)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	req := &userpb.GetUserRequest{
		Id: id,
	}

	resp, err := r.UserClient.GetUser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return &model.User{
		ID:       resp.Id,
		Username: resp.Name,
		Email:    resp.Email,
	}, nil
}

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context, id string) (*model.Portfolio, error) {
	// Only return basic portfolio info
	// Holdings and Summary will be resolved by their own field resolvers
	return &model.Portfolio{
		ID:     id,
		UserID: id,
		Name:   "My Portfolio",
	}, nil
}

// PortfolioPerformance is the resolver for the portfolioPerformance field.
func (r *queryResolver) PortfolioPerformance(ctx context.Context, userID string, period string) ([]*model.PortfolioPerformancePoint, error) {
	req := &portfoliopb.GetPortfolioPerformanceRequest{
		UserId: userID,
		Period: period,
	}

	resp, err := r.PortfolioClient.GetPortfolioPerformance(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get portfolio performance: %w", err)
	}

	var dataPoints []*model.PortfolioPerformancePoint
	for _, dp := range resp.DataPoints {
		dataPoints = append(dataPoints, &model.PortfolioPerformancePoint{
			Timestamp: dp.Timestamp.AsTime().Format("2006-01-02T15:04:05Z07:00"),
			Value:     dp.Value,
		})
	}

	return dataPoints, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Portfolio returns generated.PortfolioResolver implementation.
func (r *Resolver) Portfolio() generated.PortfolioResolver { return &portfolioResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type portfolioResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
