package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/garcios/portfolio-insights/apps/gateway/graph/generated"
	"github.com/garcios/portfolio-insights/apps/gateway/graph/mapper"
	"github.com/garcios/portfolio-insights/apps/gateway/graph/model"
	"github.com/garcios/portfolio-insights/apps/gateway/internal/auth"
	"github.com/garcios/portfolio-insights/apps/gateway/internal/domain/entity"
	"github.com/garcios/portfolio-insights/apps/gateway/internal/middleware"
)

// TargetCurrency is the resolver for the targetCurrency field.
func (r *holdingResolver) TargetCurrency(ctx context.Context, obj *entity.Holding) (string, error) {
	// Use DataLoader to fetch user preferences efficiently (avoids N+1)
	loaders := middleware.GetLoaders(ctx)
	if loaders == nil {
		return "", fmt.Errorf("dataloaders not found in context")
	}

	user, err := loaders.UserLoader.Load(ctx, obj.UserID)
	if err != nil {
		return "", fmt.Errorf("failed to load user for target currency: %w", err)
	}

	// Default to USD if not set
	currency := "USD"
	if user.Preferences != nil {
		if val, ok := user.Preferences["default_currency"].(string); ok && val != "" {
			currency = val
		}
	}

	return currency, nil
}

// CurrentValueInTargetCurrency is the resolver for the currentValueInTargetCurrency field.
func (r *holdingResolver) CurrentValueInTargetCurrency(ctx context.Context, obj *entity.Holding) (float64, error) {
	// 1. Get Target Currency (same logic as above, but we need the value here)
	targetCurrency, err := r.TargetCurrency(ctx, obj)
	if err != nil {
		return 0, err
	}

	// 2. If currencies match, no conversion needed
	if obj.Currency == targetCurrency {
		return obj.CurrentValue, nil
	}

	// 3. Get Exchange Rate using Loader (optimized/deduplicated)
	// We already fetched loaders in step 1 (implied) or we fetch again
	loaders := middleware.GetLoaders(ctx)
	if loaders == nil {
		return 0, fmt.Errorf("dataloaders not found in context")
	}

	rate, err := loaders.ExchangeRateLoader.Load(ctx, obj.Currency, targetCurrency)
	if err != nil {
		return 0, fmt.Errorf("failed to get exchange rate: %w", err)
	}

	// 4. Calculate Converted Value
	return obj.CurrentValue * rate, nil
}

// GainLossInTargetCurrency is the resolver for the gainLossInTargetCurrency field.
func (r *holdingResolver) GainLossInTargetCurrency(ctx context.Context, obj *entity.Holding) (float64, error) {
	// 1. Get Target Currency
	targetCurrency, err := r.TargetCurrency(ctx, obj)
	if err != nil {
		return 0, err
	}

	// 2. If currencies match, no conversion needed
	if obj.Currency == targetCurrency {
		return obj.GainLoss, nil
	}

	// 3. Get Exchange Rate using Loader
	loaders := middleware.GetLoaders(ctx)
	if loaders == nil {
		return 0, fmt.Errorf("dataloaders not found in context")
	}

	rate, err := loaders.ExchangeRateLoader.Load(ctx, obj.Currency, targetCurrency)
	if err != nil {
		return 0, fmt.Errorf("failed to get exchange rate: %w", err)
	}

	// 4. Calculate Converted Gain/Loss
	return obj.GainLoss * rate, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	// Default password - in production this should come from input
	user, err := r.Container.UserUseCase.CreateUser(ctx, input.Email, input.Username, input.Password, input.FirstName, input.LastName)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	return mapper.UserEntityToGraphQL(user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	// Get user ID from context
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Map input to entity updates
	updates := &entity.UserUpdate{
		Email:       input.Email,
		Username:    input.Username,
		FirstName:   input.FirstName,
		LastName:    input.LastName,
		Preferences: input.Preferences,
	}

	// Delegate to use case
	user, err := r.Container.UserUseCase.UpdateUser(ctx, userID, updates)
	if err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	return mapper.UserEntityToGraphQL(user), nil
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.NewTransaction) (*model.Transaction, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user ID from context: %w", err)
	}

	// Convert GraphQL input to use case input
	useCaseInput, err := mapper.GraphQLNewTransactionToUseCaseInput(input)
	if err != nil {
		return nil, fmt.Errorf("invalid transaction input: %w", err)
	}

	// Create transaction via use case
	tx, err := r.Container.TransactionUseCase.CreateTransaction(ctx, userID, useCaseInput)
	if err != nil {
		return nil, err
	}

	return mapper.TransactionEntityToGraphQL(tx), nil
}

// UploadTransactionCSV is the resolver for the uploadTransactionCSV field.
func (r *mutationResolver) UploadTransactionCSV(ctx context.Context, file graphql.Upload) (bool, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("failed to get user ID from context: %w", err)
	}

	if err := r.Container.TransactionUseCase.UploadCSV(ctx, userID, file.File, file.Filename); err != nil {
		return false, fmt.Errorf("failed to upload CSV: %w", err)
	}

	return true, nil
}

// Summary is the resolver for the summary field.
func (r *portfolioResolver) Summary(ctx context.Context, obj *model.Portfolio, startDate *string, endDate *string) (*model.PortfolioSummary, error) {
	// This resolver only executes if the query requests the summary field
	summary, err := r.Container.PortfolioUseCase.GetPortfolioSummary(ctx, obj.UserID, startDate, endDate)
	if err != nil {
		// Return nil for optional field if it fails
		return nil, nil
	}

	if summary == nil {
		return nil, nil
	}

	return mapper.PortfolioSummaryEntityToGraphQL(summary), nil
}

// Holdings is the resolver for the holdings field.
func (r *portfolioResolver) Holdings(ctx context.Context, obj *model.Portfolio) ([]*entity.Holding, error) {
	// This resolver only executes if the query requests the holdings field
	holdings, err := r.Container.PortfolioUseCase.GetHoldings(ctx, obj.UserID)
	if err != nil {
		return nil, fmt.Errorf("failed to get holdings: %w", err)
	}

	// Return entities directly, gqlgen handles mapping to model/interface if bound
	return holdings, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := r.Container.UserUseCase.GetCurrentUser(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get current user: %w", err)
	}

	return mapper.UserEntityToGraphQL(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user, err := r.Container.UserUseCase.GetUser(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return mapper.UserEntityToGraphQL(user), nil
}

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context) (*model.Portfolio, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user ID from context: %w", err)
	}

	// Get portfolio from use case
	portfolio, err := r.Container.PortfolioUseCase.GetPortfolio(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get portfolio: %w", err)
	}

	return mapper.PortfolioEntityToGraphQL(portfolio), nil
}

// PortfolioPerformance is the resolver for the portfolioPerformance field.
func (r *queryResolver) PortfolioPerformance(ctx context.Context, period string) ([]*model.PortfolioPerformancePoint, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user ID from context: %w", err)
	}

	dataPoints, err := r.Container.PortfolioUseCase.GetPortfolioPerformance(ctx, userID, period)
	if err != nil {
		return nil, fmt.Errorf("failed to get portfolio performance: %w", err)
	}

	return mapper.PortfolioPerformancePointEntitiesToGraphQL(dataPoints), nil
}

// ListTransactions is the resolver for the listTransactions field.
func (r *queryResolver) ListTransactions(ctx context.Context, pageSize *int, pageToken *string, filter *model.TransactionFilterInput) (*model.TransactionConnection, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user ID from context: %w", err)
	}

	// Convert GraphQL filter to gateway filter
	gatewayFilter, err := mapper.GraphQLTransactionFilterToGatewayFilter(filter)
	if err != nil {
		return nil, fmt.Errorf("invalid filter: %w", err)
	}

	// Set default page size if not provided
	size := int32(50)
	if pageSize != nil {
		size = int32(*pageSize)
	}

	// Get page token
	token := ""
	if pageToken != nil {
		token = *pageToken
	}

	// Call use case
	result, err := r.Container.TransactionUseCase.ListTransactions(ctx, userID, size, token, gatewayFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to list transactions: %w", err)
	}

	return mapper.ListTransactionsResultToGraphQL(result), nil
}

// Holding returns generated.HoldingResolver implementation.
func (r *Resolver) Holding() generated.HoldingResolver { return &holdingResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Portfolio returns generated.PortfolioResolver implementation.
func (r *Resolver) Portfolio() generated.PortfolioResolver { return &portfolioResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type holdingResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type portfolioResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
