directive @auth(scopes: [String!]) on FIELD_DEFINITION

type Query {
  me: User @auth
  user(id: ID!): User @auth
  portfolio: Portfolio @auth
  portfolioPerformance(period: String!): [PortfolioPerformancePoint!]! @auth
  listTransactions(
    pageSize: Int
    pageToken: String
    filter: TransactionFilterInput
  ): TransactionConnection! @auth
}

type Mutation {
  createUser(input: NewUser!): User!
  createTransaction(input: NewTransaction!): Transaction! @auth
  uploadTransactionCSV(file: Upload!): Boolean! @auth
}

scalar Upload

type User {
  id: ID!
  username: String!
  email: String!
}

type Portfolio {
  id: ID!
  userId: ID!
  name: String!
  summary: PortfolioSummary
  holdings: [Holding!]!
}

type PortfolioSummary {
  totalValue: Float!
  totalGainLoss: Float!
  totalGainLossPercentage: Float!
  dayChange: Float!
  dayChangePercentage: Float!
  currency: String!
  lastUpdated: String!
}

type Holding {
  symbol: String!
  quantity: Float!
  averagePrice: Float!
  currentPrice: Float!
  currentValue: Float!
  gainLoss: Float!
  gainLossPercentage: Float!
  currency: String!
  assetName: String!
}

input NewUser {
  username: String!
  email: String!
  password: String!
}

type PortfolioPerformancePoint {
  timestamp: String!
  value: Float!
}

enum TransactionType {
  BUY
  SELL
  SPLIT
  DIVIDEND
}

type Transaction {
  id: ID!
  userId: ID!
  symbol: String!
  type: TransactionType!
  quantity: Float!
  pricePerShare: Float!
  executedAt: String!
  notes: String
  brokerage: Float
  priceCurrency: String
  brokerageCurrency: String
  createdAt: String!
  updatedAt: String!
}

input NewTransaction {
  symbol: String!
  quantity: Float!
  pricePerShare: Float!
  executedAt: String!
  type: TransactionType!
  notes: String
  brokerage: Float
  priceCurrency: String
  brokerageCurrency: String
}

input TransactionFilterInput {
  symbol: String
  type: TransactionType
  fromExecutedAt: String
  toExecutedAt: String
}

type TransactionConnection {
  transactions: [Transaction!]!
  nextPageToken: String
}
