version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: garcios
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    command: "-js"
    ports:
      - "4222:4222"
      - "8222:8222"

  gateway:
    build:
      context: ../../
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - portfolio-service

  user-service:
    build:
      context: ../../
      dockerfile: services/user-service/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_USER=garcios
      - DB_PASSWORD=Password123
      - DB_NAME=portfolio
    depends_on:
      - postgres

  portfolio-service:
    build:
      context: ../../
      dockerfile: services/portfolio-service/Dockerfile
    ports:
      - "50052:50052"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data

  marketdata-service:
    build:
      context: ../../
      dockerfile: services/marketdata-service/Dockerfile
    ports:
      - "50054:50054"
    environment:
      - DB_HOST=postgres
      - DB_USER=garcios
      - DB_PASSWORD=Password123
      - DB_NAME=portfolio
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=market-data
    depends_on:
      - postgres
      - minio

  transaction-service:
    build:
      context: ../../
      dockerfile: services/transaction-service/Dockerfile
    ports:
      - "50053:50053"
    environment:
      - DB_HOST=postgres
      - DB_USER=garcios
      - DB_PASSWORD=Password123
      - DB_NAME=portfolio
      - PORT=50053
    depends_on:
      - postgres

volumes:
  postgres_data:
  minio_data:
