{{- if .Values.prometheus.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "observability.fullname" . }}-prometheus-data
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.prometheus.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size | quote }}
  {{- if .Values.prometheus.persistence.storageClass }}
  storageClassName: {{ .Values.prometheus.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "observability.fullname" . }}-grafana-data
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.grafana.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size | quote }}
  {{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.alertmanager.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "observability.fullname" . }}-alertmanager-data
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.alertmanager.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.alertmanager.persistence.size | quote }}
  {{- if .Values.alertmanager.persistence.storageClass }}
  storageClassName: {{ .Values.alertmanager.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
