port: "50053"
http_port: "8081"
metrics_port: "9097"
log_level: "debug"

db_host: "localhost"
db_port: "5432"
db_user: "garcios"
db_password: "Password123"
db_name: "portfolio"
db_sslmode: "disable"

user_service_addr: "localhost:50051"
marketdata_service_addr: "localhost:50054"

nats_url: "nats://localhost:4222"
transaction_topic: "transaction-service.transaction.created"
